version: "main"
services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
     - '3000:3000'
volumes:
  grafana-storage: {}
