#=================================================
# NOTE: Secrets should not be stored in your repo
# Ensure to base64 encode any `data` values, `stringData` are plain UTF strings
#=================================================
apiVersion: v1
kind: Secret
metadata:
  name: pg-secret
type: Opaque
stringData:
  POSTGRES_USER: ""
  POSTGRES_PASSWORD: ""
  DATABASE_URL: postgresql://username:password@zen-pg-svc:5432/zen
---
apiVersion: v1
kind: Secret
metadata:
  name: zen-jwt
type: Opaque
data: # Requires base64 encoded strings
  JWT_PRIVATE_KEY: "" # ECDSA using P-256 curve and SHA-256 hash algorithm
  JWT_PUBLIC_KEY: "" # Refer to NOTES.md for instructions of how to generate keys using openssl
---
apiVersion: v1
kind: Secret
metadata:
  name: zen-google-oauth
type: Opaque
stringData: # https://developers.google.com/identity/protocols/oauth2/openid-connect
  GOOGLE_CLIENT_ID: ""
  GOOGLE_CLIENT_SECRET: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: zen-smtp
type: Opaque
stringData:
  SMTP_SERVER: ""
  SMTP_LOGIN: ""
  SMTP_PASSWORD: ""
  SMTP_FROM_NAME: ""
  SMTP_FROM_EMAIL: ""
